# netlify.toml - Performance & Security Optimierung für maier-value.com
# Version: 1.0 - Core Web Vitals Optimierung

[build]
  command = "npm run build"
  publish = "dist"

# Performance-optimierte Redirects
[[redirects]]
  from = "/blog/old-post"
  to = "/blog/new-post"
  status = 301

# Security & Performance Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance Headers
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Statische Assets - Lange Cache-Zeit
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Bilder - Mittlere Cache-Zeit
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# HTML-Dateien - Kurze Cache-Zeit für Aktualität
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Service Worker Support
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"